###### 1.   In the github Assignment section, you will get a data set named Assignment_10_data. Download the data and perform the following operation.

1. import the data set

2. Show the full data set using python pandas function.

3. Create another data frame from given data set that contain only 2 columns. Also convert the data frame to CSV

4. Find out number of null values of the given data sets and also show the mean and standard deviation.

5. Create a data frame that contain the 51th to 120th row.

6. Make a new dataset that you get from 5 no

In [35]:
import pandas as pd
ds = pd.read_csv("Assignment_10_data.csv")
ds.head()

  Station_Names  YEAR  Month  Temprature    Rainfall
0         Bogra  1948      1        25.8    8.140625
1         Bogra  1948      2        33.3   11.140625
2         Bogra  1948      3        38.3   25.312500
3         Bogra  1948      4        39.5   69.140625
4         Bogra  1948      5        36.1  179.890625

In [ ]:
new_ds = ds[['YEAR','Month']]
new_ds.head()

In [19]:
new_ds.to_csv('New_Dataset.csv')

In [ ]:
ds.info()

In [ ]:
ds.describe()

In [26]:
df = ds.iloc[51:121]

In [ ]:
df.to_csv('New_Dataset2.csv')

###### 2. Create a data frame that contain Id, Name, Department, Result of minimum 5 persons. Then convert the data frame to a CSV file and excel file.

In [ ]:
data = {"ID": [1, 2, 3, 4, 5],
        "Name": ['Fahim', 'Hasan', 'Karim', 'Jasim', 'Rahim'],
        "Dept.": ['CSE', 'EEE', 'BBA', 'ETE', 'CCE'],
        "Result": [3.23, 3.56, 3.00, 3.15, 3.86]}
df = pd.DataFrame(data)
df

In [30]:
df.to_csv('Dataset.csv')

In [31]:
df.to_excel('Dataset.xlsx')

###### 3. Import the excel file and perform the operation that is given in the previous question.

In [ ]:
df = pd.read_excel('Dataset.xlsx')
df