In [ ]:
# importing packages
import pandas as pd

In [ ]:
# importing dataset
dataset = pd.read_csv("diabetes.csv")

In [ ]:
print(f"dataset Shape {dataset.shape}")

dataset Shape (1523, 8)

In [ ]:
# First 10 rows
dataset.head(10)

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0.0,1,25.19,6.6,140,0
1,Female,54.0,0.0,0,27.32,6.6,80,0
2,Male,28.0,0.0,0,27.32,5.7,158,0
3,Female,36.0,0.0,0,NaN,5.0,155,0
4,Male,76.0,1.0,1,NaN,4.8,155,0
5,Female,20.0,0.0,0,NaN,6.6,85,0
6,Female,44.0,0.0,0,19.31,6.5,200,1
7,Female,79.0,0.0,0,NaN,5.7,85,0
8,Male,42.0,0.0,0,33.64,4.8,145,0
9,NaN,32.0,0.0,0,NaN,5.0,100,0

In [ ]:
# Last 10 rows
dataset.tail(10)

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
1513,Male,52.0,0.0,0,NaN,6.0,140,0
1514,Male,80.0,0.0,1,27.94,3.5,158,0
1515,Male,80.0,1.0,0,NaN,6.2,80,0
1516,Male,31.0,1.0,0,NaN,4.0,145,0
1517,Female,31.0,0.0,0,27.32,6.6,140,0
1518,Female,47.0,0.0,0,25.64,6.0,140,0
1519,Female,80.0,0.0,0,28.66,5.0,200,0
1520,Female,59.0,0.0,0,27.32,6.0,130,0
1521,Male,80.0,0.0,1,27.32,6.5,200,0
1522,Female,68.0,1.0,0,27.92,4.8,100,0

In [ ]:
# information about columns
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1523 entries, 0 to 1522
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               1442 non-null   object
 1   age                  1523 non-null   float64
 2   hypertension         1506 non-null   float64
 3   heart_disease        1523 non-null   int64
 4   bmi                  773 non-null    float64
 5   HbA1c_level          1523 non-null   float64
 6   blood_glucose_level  1523 non-null   int64
 7   diabetes             1523 non-null   int64
dtypes: float64(4), int64(3), object(1)
memory usage: 95.3+ KB

In [ ]:
# statistical measurement
dataset.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,1523.000000,1506.000000,1523.000000,773.000000,1523.000000,1523.000000,1523.000000
mean,41.311989,0.073705,0.034800,26.549754,5.555483,139.136573,0.084701
std,22.800735,0.261377,0.183332,6.296258,1.119784,39.703166,0.278528
min,0.080000,0.000000,0.000000,13.020000,3.500000,80.000000,0.000000
25%,23.000000,0.000000,0.000000,22.600000,4.800000,100.000000,0.000000
50%,42.000000,0.000000,0.000000,27.320000,5.800000,145.000000,0.000000
75%,59.000000,0.000000,0.000000,28.270000,6.200000,159.000000,0.000000
max,80.000000,1.000000,1.000000,57.170000,9.000000,300.000000,1.000000

## Missing value

In [ ]:
# Count missing data
dataset.isna().sum()

gender                  81
age                      0
hypertension            17
heart_disease            0
bmi                    750
HbA1c_level              0
blood_glucose_level      0
diabetes                 0
dtype: int64

In [ ]:
# categorical missing value
dataset['gender'] = dataset['gender'].fillna(dataset['gender'].mode())

In [ ]:
# Numerical Missing value
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='median')

dataset[['hypertension','bmi']] = imp_mean.fit_transform(dataset[['hypertension','bmi']])

# Encoding

In [ ]:

dataset["gender"].unique()

array(['Female', 'Male', nan], dtype=object)

In [ ]:
# Changing categorical into numerical
dataset["gender"] = dataset["gender"].map({"Other": 0, "Male": 1,"Female": 2})
dataset.head()

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
0,2.0,80.0,0.0,1,25.19,6.6,140,0
1,2.0,54.0,0.0,0,27.32,6.6,80,0
2,1.0,28.0,0.0,0,27.32,5.7,158,0
3,2.0,36.0,0.0,0,27.32,5.0,155,0
4,1.0,76.0,1.0,1,27.32,4.8,155,0

# Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

dataset[['age','bmi','blood_glucose_level']] = scaler.fit_transform(dataset[['age','bmi','blood_glucose_level']])

In [ ]:
dataset.head()

,gender,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
0,2.0,1.000000,0.0,1,0.275651,6.6,0.272727,0
1,2.0,0.674675,0.0,0,0.323896,6.6,0.000000,0
2,1.0,0.349349,0.0,0,0.323896,5.7,0.354545,0
3,2.0,0.449449,0.0,0,0.323896,5.0,0.340909,0
4,1.0,0.949950,1.0,1,0.323896,4.8,0.340909,0